WIP: Feature/custom signet
romanz/electrs pull request #762
Opened 2022-08-16 13:54 UTC by Sosthene00

This PR attempts to solve the issue raised in #418 
It is pretty straightforward, a `signet_magic` can be added as an option. If it is not set the magic is the default value for the network (`network.magic()`).
It is not fully operational though, I tried to run it against a custom signet and it seems that it downloads some blocks then fails for some reason. Here's the full log of a typical run:
```
Starting electrs 0.9.8 on x86_64 linux with Config { network: Signet, db_path: "/home/electrs/db/signet", daemon_dir: "/data/signet", daemon_auth: CookieFile("/data/signet/.cookie"), daemon_rpc_addr: 192.168.240.3:38332, daemon_p2p_addr: 192.168.240.3:38333, electrum_rpc_addr: 127.0.0.1:60601, monitoring_addr: 127.0.0.1:34224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.9.8 (Electrum Rust Server)!", signet_magic: 3278571876, args: [] }
[2022-08-16T13:50:01.595Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:34224
[2022-08-16T13:50:01.595Z INFO  electrs::server] serving Electrum RPC on 127.0.0.1:60601
[2022-08-16T13:50:01.601Z DEBUG tiny_http] Server listening on 127.0.0.1:34224
[2022-08-16T13:50:01.606Z DEBUG tiny_http] Running accept thread
[2022-08-16T13:50:01.670Z INFO  electrs::db] "/home/electrs/db/signet": 13 SST files, 0.000010465 GB, 0.000000013 Grows
[2022-08-16T13:50:01.670Z DEBUG electrs::db] DB Some(Config { compacted: false, format: 0 })
[2022-08-16T13:50:01.688Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockchaininfo []
[2022-08-16T13:50:01.689Z DEBUG bitcoincore_rpc] JSON-RPC error for getblockchaininfo: RpcError { code: -28, message: "Loading wallet…", data: None }
[2022-08-16T13:50:01.689Z INFO  electrs::daemon] waiting for RPC warmup: Loading wallet…
[2022-08-16T13:50:02.691Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockchaininfo []
[2022-08-16T13:50:02.692Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
[2022-08-16T13:50:02.692Z INFO  electrs::daemon] waiting for 117 blocks to download
[2022-08-16T13:50:03.692Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockchaininfo []
[2022-08-16T13:50:03.722Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
[2022-08-16T13:50:03.723Z INFO  electrs::daemon] waiting for 96 blocks to download
[2022-08-16T13:50:04.729Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockchaininfo []
[2022-08-16T13:50:04.730Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
[2022-08-16T13:50:04.771Z INFO  electrs::daemon] waiting for 85 blocks to download
[2022-08-16T13:50:05.778Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockchaininfo []
[2022-08-16T13:50:05.799Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
[2022-08-16T13:50:05.800Z INFO  electrs::daemon] waiting for 69 blocks to download
[2022-08-16T13:50:06.814Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockchaininfo []
[2022-08-16T13:50:06.829Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
[2022-08-16T13:50:06.830Z INFO  electrs::daemon] waiting for 56 blocks to download
[2022-08-16T13:50:07.832Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockchaininfo []
[2022-08-16T13:50:07.834Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
[2022-08-16T13:50:07.835Z INFO  electrs::daemon] waiting for 45 blocks to download
[2022-08-16T13:50:08.836Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockchaininfo []
[2022-08-16T13:50:08.837Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
[2022-08-16T13:50:08.838Z INFO  electrs::daemon] waiting for 34 blocks to download
[2022-08-16T13:50:09.840Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockchaininfo []
[2022-08-16T13:50:09.858Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
[2022-08-16T13:50:09.859Z INFO  electrs::daemon] waiting for 23 blocks to download
[2022-08-16T13:50:10.861Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockchaininfo []
[2022-08-16T13:50:10.958Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
[2022-08-16T13:50:10.960Z INFO  electrs::daemon] waiting for 2 blocks to download
[2022-08-16T13:50:11.975Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockchaininfo []
[2022-08-16T13:50:11.977Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
[2022-08-16T13:50:11.978Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
[2022-08-16T13:50:11.978Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockchaininfo []
[2022-08-16T13:50:11.979Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
[2022-08-16T13:50:11.981Z DEBUG electrs::p2p] closing p2p_recv thread: connection closed
[2022-08-16T13:50:11.981Z DEBUG electrs::p2p] closing p2p_loop thread: peer has disconnected
[2022-08-16T13:50:11.981Z INFO  electrs::db] closing DB at /home/electrs/db/signet
Error: electrs failed

Caused by:
    receiving on an empty and disconnected channel
```

I run electrs and bitcoin core in a docker compose.

2022-08-16 14:32 UTC, Sosthene00 commented
Silly me, I got the endianness wrong on the magic. It's working now.
That being said I'd rather pass the magic as it is in bitcoin log and reversing it inside electrs.

2022-08-31 18:27 UTC, romanz commented
Please cherry-pick https://github.com/romanz/electrs/commit/c05b56846f796ba72352739f655b12b1999716f5 (for fixing CI)

2022-08-31 18:29 UTC, romanz requested changes
Please cherry-pick https://github.com/romanz/electrs/commit/c05b56846f796ba72352739f655b12b1999716f5 (for fixing CI)

2022-09-01 17:54 UTC, romanz approved these changes

2022-09-01 17:55 UTC, merged